### ISSUE TITLE
Listing all the Metrics Doesn't Work

### ISSUE THREAD

**Issue by chavenor** [StackStorm-Exchange/stackstorm-librato#2] opened 2017-06-30 05:30 UTC
This is the only action that I tried. 

The action completes but the results are None.  Which isn't the case I have some metrics in my account.  I tested this in my python shell as I've been adding metrics to my account.  

No errors in grep -i error /var/log/st2/*.log or grep -i error /var/log/st2/st2actionrunner*.log

**Comment by LindsayHill** [comment] 2017-07-27 02:47
I've just done some checks here, and this seems to work.

Here's what I did:

1. Signed up for trial Librato account
2. Installed the Ubuntu agent on an Ubuntu 14.04 system
3. Generated a new read-only API token
4. Installed the Librato pack on my system (`st2 pack install librato`)
5. Configured the pack with `st2 pack config librato`. I provided my API token & my email address.
6. I then tried running `st2 run librato.list_metrics`, and it works:

```bash
vagrant@bwcvagrant:~$ st2 run librato.list_metrics
..
id: 59795329bb0f1805267d4a74
status: succeeded
parameters: None
result:
  exit_code: 0
  result: '[Gauge<librato.cpu.percent.idle>, Gauge<librato.cpu.percent.interrupt>, Gauge<librato.cpu.percent.nice>, Gauge<librato.cpu.percent.softirq>, Gauge<librato.cpu.percent.steal>, Gauge<librato.cpu.percent.system>, Gauge<librato.cpu.percent.user>, Gauge<librato.cpu.percent.wait>, Gauge<librato.df.percent_bytes.free>, Gauge<librato.df.percent_bytes.reserved>, Gauge<librato.df.percent_bytes.used>, Gauge<librato.disk.disk_io_time.io_time>, Gauge<librato.disk.disk_io_time.weighted_io_time>, Gauge<librato.disk.disk_merged.read>, Gauge<librato.disk.disk_merged.write>, Gauge<librato.disk.disk_octets.read>, Gauge<librato.disk.disk_octets.write>, Gauge<librato.disk.disk_ops.read>, Gauge<librato.disk.disk_ops.write>, Gauge<librato.disk.disk_time.read>, Gauge<librato.disk.disk_time.write>, Gauge<librato.interface.if_dropped.rx>, Gauge<librato.interface.if_dropped.tx>, Gauge<librato.interface.if_errors.rx>, Gauge<librato.interface.if_errors.tx>, Gauge<librato.interface.if_octets.rx>, Gauge<librato.interface.if_octets.tx>, Gauge<librato.interface.if_packets.rx>, Gauge<librato.interface.if_packets.tx>, Gauge<librato.load.load.longterm>, Gauge<librato.load.load.midterm>, Gauge<librato.load.load.shortterm>, Gauge<librato.memory.memory.buffered>, Gauge<librato.memory.memory.cached>, Gauge<librato.memory.memory.free>, Gauge<librato.memory.memory.slab_recl>, Gauge<librato.memory.memory.slab_unrecl>, Gauge<librato.memory.memory.used>, Gauge<librato.swap.swap.cached>, Gauge<librato.swap.swap.free>, Gauge<librato.swap.swap.used>, Counter<librato.swap.swap_io.in>, Counter<librato.swap.swap_io.out>]}'
  stderr: ''
  stdout: ''
vagrant@bwcvagrant:~$
```

Things to check - check your configuration in `/opt/stackstorm/configs/librato.yaml`. It should look something like this:
```yaml
token: 7797c3a6d73b30b34832480329845032abdedab22abd8402341
user: lindsay@stackstorm.com
```

Make sure the configuration is loaded, with `sudo st2ctl reload --register-configs`.

Double-check those steps, and see if that works. If it doesn't, we can look at some more debugging steps.

**Comment by chavenor** [comment] 2017-07-27 11:08
Are you saying that listing the metrics for the account only works on the machine that I'm calling it on? 

We might want to update the docs to explain that you have to have the agent on the system before you make the call I assumed I could call against the API directly and will be able to pull metrics and data.

**Comment by LindsayHill** [comment] 2017-07-27 11:18
No, you absolutely do not need the agent on the same system. I just installed the agent so I would have some metrics to query

**Comment by chavenor** [comment] 2017-07-27 18:49
I will test it again this weekend let you know how goes

**Comment by chavenor** [comment] 2017-07-31 23:34
I tested it again and it didn't seem to be able to find my custom metrics in return non-when I use the UI to list the metrics from Librado account

**Comment by LindsayHill** [comment] 2017-08-01 15:05
So when you run `st2 run librato.list_metrics`, what results are you getting?

**Comment by chavenor** [comment] 2017-08-01 15:07
```
id: 59809901d93a1f7ce2397d75
status: succeeded
parameters: None
result:
  exit_code: 0
  result: None
  stderr: ''
  stdout: ''
```

**Comment by LindsayHill** [comment] 2017-08-01 22:42
When you created your API token, what permissions did you give it? 

What happens if you enter the librato virtualenv (with `source /opt/stackstorm/virtualenvs/librato/bin/activate`, followed by this interactive Python code? (Update your username/token of course)

```python
import librato
user = '<your_librato_user>'
token = '<your_token>'
client = librato.connect(user, token)
client.list_metrics()
```

Your session should look something like this:
```sh
vagrant@st2vagrant:~$ source /opt/stackstorm/virtualenvs/librato/bin/activate
(librato) vagrant@st2vagrant:~$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import librato
>>> user='lindsay@stackstorm.com'
>>> token='7797c3a6d73b30b34832480329845032abdedab22abd8402341'
>>> client = librato.connect(user, token)
>>> client.list_metrics()
[Gauge<librato.cpu.percent.idle>, Gauge<librato.cpu.percent.interrupt>, Gauge<librato.cpu.percent.nice>, Gauge<librato.cpu.percent.softirq>, Gauge<librato.cpu.percent.steal>, Gauge<librato.cpu.percent.system>, Gauge<librato.cpu.percent.user>, Gauge<librato.cpu.percent.wait>, Gauge<librato.df.percent_bytes.free>, Gauge<librato.df.percent_bytes.reserved>, Gauge<librato.df.percent_bytes.used>, Gauge<librato.disk.disk_io_time.io_time>, Gauge<librato.disk.disk_io_time.weighted_io_time>, Gauge<librato.disk.disk_merged.read>, Gauge<librato.disk.disk_merged.write>, Gauge<librato.disk.disk_octets.read>, Gauge<librato.disk.disk_octets.write>, Gauge<librato.disk.disk_ops.read>, Gauge<librato.disk.disk_ops.write>, Gauge<librato.disk.disk_time.read>, Gauge<librato.disk.disk_time.write>, Gauge<librato.disk.pending_operations>, Gauge<librato.interface.if_dropped.rx>, Gauge<librato.interface.if_dropped.tx>, Gauge<librato.interface.if_errors.rx>, Gauge<librato.interface.if_errors.tx>, Gauge<librato.interface.if_octets.rx>, Gauge<librato.interface.if_octets.tx>, Gauge<librato.interface.if_packets.rx>, Gauge<librato.interface.if_packets.tx>, Gauge<librato.load.load.longterm>, Gauge<librato.load.load.midterm>, Gauge<librato.load.load.shortterm>, Gauge<librato.memory.memory.buffered>, Gauge<librato.memory.memory.cached>, Gauge<librato.memory.memory.free>, Gauge<librato.memory.memory.slab_recl>, Gauge<librato.memory.memory.slab_unrecl>, Gauge<librato.memory.memory.used>, Gauge<librato.swap.swap.cached>, Gauge<librato.swap.swap.free>, Gauge<librato.swap.swap.used>, Counter<librato.swap.swap_io.in>, Counter<librato.swap.swap_io.out>]
>>>
vagrant@st2vagrant:~$
```

If that *doesn't* work, then something is going wrong below the ST2 level (e.g. some issue with your Librato account/permissions, or proxy, or something else). If that *does* work, then it's something ST2-related.

**Comment by chavenor** [comment] 2017-08-01 23:21
Token has full access.

The account was created through heroku.  I have multiple platforms attached to my account at the highest level perhaps it's not able to just gather all the metrics from all the different platforms.

**Comment by LindsayHill** [comment] 2017-08-01 23:24
Possible. What happens if you manually try listing metrics, using the Python snippet above? 

Also see if any of the other python-librato actions work, e.g. listing spaces

Wonder if something else is going on, e.g. too many metrics causing problems for the library?

**Comment by chavenor** [comment] 2017-08-01 23:30
I'm getting a list back with a bunch of metrics and it. 

```python
[Gauge<active-connections>, Metric<app-availability>, Metric<app-error-percentage>, Gauge<db_size>, Gauge<digtialocean_machine_count>, Gauge<errors.ht tp.h10>, Gauge<errors.http.h11>, Gauge<errors.http.h12>, Gauge<errors.http.h13>, Gauge<errors.http.h14>, Gauge<errors.http.h15>, Gauge<errors.http.h16 >, Gauge<errors.http.h17>, Gauge<errors.http.h18>, Gauge<errors.http.h19>, Gauge<errors.http.h20>, Gauge<errors.http.h21>, Gauge<errors.http.h22>, Gau ge<errors.http.h23>, Gauge<errors.http.h24>, Gauge<errors.http.h25>, Gauge<errors.http.h26>, Gauge<errors.http.h27>, Gauge<errors.http.h28>, Gauge<err ors.http.h80>, Gauge<errors.http.h81>, Gauge<errors.http.h82>, Gauge<errors.http.h99>, Gauge<errors.logging.l10>, Gauge<errors.logging.l11>, Gauge<err ors.logging.l12>, Gauge<errors.logging.l13>, Gauge<errors.logging.l14>, Gauge<errors.runtime.r10>, Gauge<errors.runtime.r12>, Gauge<errors.runtime.r13 >, Gauge<errors.runtime.r14>, Gauge<errors.runtime.r15>, Gauge<errors.runtime.r151>, Gauge<errors.runtime.r16>, Gauge<errors.runtime.r99>, Gauge<index -cache-hit-rate>, Gauge<load-avg-15m>, Gauge<load-avg-1m>, Gauge<load-avg-5m>, Gauge<load_avg_15m>, Gauge<load_avg_1m>, Gauge<load_avg_5m>, Gauge<memo ry-cached>, Gauge<memory-free>, Gauge<memory-postgres>, Gauge<memory-total>, Gauge<memory_cache>, Gauge<memory_pgpgin>, Gauge<memory_pgpgout>, Gauge<m emory_rss>, Gauge<memory_swap>, Gauge<memory_total>, Gauge<nginx.service>, Gauge<nginx.service.median>, Gauge<nginx.service.perc95>, Gauge<nginx.servi ce.perc99>, Gauge<proxy.record_exists>, Gauge<proxy.record_saved>, Gauge<router.bytes>, Gauge<router.bytes.median>, Gauge<router.bytes.perc95>, Gauge< router.bytes.perc99>, Gauge<router.connect>, Gauge<router.connect.median>, Gauge<router.connect.perc95>, Gauge<router.connect.perc99>, Gauge<router.se rvice>, Gauge<router.service.median>, Gauge<router.service.perc95>, Gauge<router.service.perc99>, Gauge<router.status.2xx>, Gauge<router.status.3xx>, Gauge<router.status.4xx>, Gauge<router.status.5xx>, Gauge<spam-score>, Gauge<spam-score-run>, Gauge<table-cache-hit-rate>, Gauge<tables>, Gauge<test.m e>, Gauge<waiting-connections>]
```

**Comment by LindsayHill** [comment] 2017-08-02 02:09
That...doesn't make much sense. The ST2 action is basically just doing the same as that snippet above. No magic involved.

Can you make these changes to list_metrics.py:
```python
from lib import action


class ListMetrics(action.LibratoBaseAction):
    def run(self):
        print self.librato.username
        print self.librato.api_key
        print self.librato.list_metrics()
        return self.librato.list_metrics()
```

Then run `st2 run librato.list_metrics`. Check that the printed username & token are what you expect.

Then run `st2 execution get <ID> -j`, using whatever `ID` was displayed when you executed the `st2 run ...` command.

Paste the output of that here, masking your username & token.

**Comment by LindsayHill** [comment] 2017-08-02 02:10
One other thing: Do you have any proxies in this environment?

**Comment by chavenor** [comment] 2017-08-02 02:10
No.

**Comment by LindsayHill** [comment] 2017-08-02 02:16
Ta. Because they can foul things up. Let us know how you get on running the changes + commands above

**Comment by chavenor** [comment] 2017-08-02 08:50
Have you tried custom metrics yet Within different settings and
environments?

**Comment by LindsayHill** [comment] 2017-08-02 14:55
I don't know what would be different about 'custom metrics' - give me an example of a 'custom metric' you've added, and I can add that to my system, and query that.

I'm also not sure what you mean by different settings and environments? Which settings/environments in Librato?

Have you run the commands I asked for earlier?

**Comment by chavenor** [comment] 2017-08-03 00:56
No I haven't had a chance I'll try to get to it this weekend or next week

**Comment by LindsayHill** [comment] 2017-09-14 01:06
Have you had a chance to look at this?

**Comment by chavenor** [comment] 2017-09-14 23:42
no I'm pretty swamped in the middle of moving and building a house and remodeling a condo for renters.

**Comment by LindsayHill** [comment] 2017-09-16 23:02
OK. I'll close this for now. If/when you get a chance to reproduce, re-open if needed.

**Closed as completed by LindsayHill** 2017-09-16 23:02 UTC
Labels: status:needs more info
